[package]
name = "do-not-publish/price-point"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Baseline = "fizzyhex/baseline@0.2.2"
Trove = "sleitnick/trove@0.5.0"
Signal = "sleitnick/signal@1.5.0"
Fusion = "elttob/fusion@0.2.0"
Promise = "evaera/promise@4.0.0"
Red = "red-blox/red@2.0.0-rc.1"
TableUtil = "sleitnick/table-util@1.2.0"
Component = "sleitnick/component@2.4.6"
Observers = "sleitnick/observers@0.3.2"