local NETWORK_NAMESPACES = {
    ROUND_STATE_CONTAINER = "RoundState",
    SCORE_STATE_CONTAINER = "ScoreState",
    GUESS_STATE_CONTAINER = "GuessState",
    PRODUCT_FEED_STATE_CONTAINER = "ProductFeedState",
    GUESS_SUBMISSION = "Guess",
    SCOREBOARD = "Scores"
}

return NETWORK_NAMESPACES